"""
deployment/generate_package.py

Takes a Mode 1 (or Mode 2) result and produces a self-contained
deployment.zip: model + preprocessing pipeline + a ready-to-run FastAPI
app + Dockerfile + docker-compose.yml + requirements.txt + README +
metrics.json + an OpenAPI spec. The idea (per spec): the company just
replaces their previous deployment with this one -- no code changes.

Note on scope: the Dockerfile/docker-compose here are correct and
buildable, but this sandbox has no Docker daemon, so "docker compose up"
itself isn't run/tested here -- only the FastAPI app inside it is (via
uvicorn directly). Treat the Docker layer as reviewed-correct config,
not as something verified running in this environment.
"""

import json
import shutil
import joblib
from pathlib import Path
from datetime import datetime, timezone


FASTAPI_APP_TEMPLATE = '''"""
Auto-generated serving app for project: {project_name}
Algorithm: {algorithm} | Problem type: {problem_type}
Generated by AIMLP Mode 1/2 on {generated_at}
"""
import joblib
import pandas as pd
from pathlib import Path
from fastapi import FastAPI
from pydantic import BaseModel
from typing import List, Dict, Any

APP_DIR = Path(__file__).parent
model = joblib.load(APP_DIR / "model.pkl")
preprocessor = joblib.load(APP_DIR / "preprocessing.pkl")
label_encoder = None
if (APP_DIR / "label_encoder.pkl").exists():
    label_encoder = joblib.load(APP_DIR / "label_encoder.pkl")

app = FastAPI(title="{project_name} — {algorithm}", version="1.0.0")


class PredictRequest(BaseModel):
    records: List[Dict[str, Any]]  # list of row dicts, same columns as training data (minus target)


@app.post("/predict")
def predict(req: PredictRequest):
    df = pd.DataFrame(req.records)
    X = preprocessor.transform(df)
    preds = model.predict(X)
    if label_encoder is not None:
        preds = label_encoder.inverse_transform(preds)
    result = {{"predictions": preds.tolist()}}
    if hasattr(model, "predict_proba"):
        try:
            result["probabilities"] = model.predict_proba(X).tolist()
        except Exception:
            pass
    return result


@app.get("/health")
def health():
    return {{"status": "ok", "algorithm": "{algorithm}", "problem_type": "{problem_type}"}}


@app.get("/")
def root():
    return {{"message": "{project_name} model server. POST /predict, GET /health."}}
'''

DOCKERFILE_TEMPLATE = """FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
"""

COMPOSE_TEMPLATE = """version: "3.9"
services:
  model-server:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PROJECT_NAME={project_name}
"""

REQUIREMENTS_TEMPLATE = """fastapi
uvicorn
scikit-learn
pandas
numpy
joblib
xgboost
lightgbm
catboost
"""

OPENAPI_SPEC_TEMPLATE = {
    "openapi": "3.0.0",
    "info": {"title": "{project_name} model server", "version": "1.0.0"},
    "paths": {
        "/predict": {
            "post": {
                "summary": "Run predictions",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {"records": {"type": "array", "items": {"type": "object"}}},
                            }
                        }
                    }
                },
                "responses": {"200": {"description": "Predictions"}},
            }
        },
        "/health": {"get": {"summary": "Health check", "responses": {"200": {"description": "OK"}}}},
    },
}

README_TEMPLATE = """# {project_name} — Deployment Package

Auto-generated by AIMLP on {generated_at}.

- **Algorithm:** {algorithm}
- **Problem type:** {problem_type}
- **Overall score:** {overall_score}/100

## Contents
- `model.pkl` — trained model
- `preprocessing.pkl` — fitted preprocessing pipeline (impute/encode/scale)
- `label_encoder.pkl` — target label encoder (classification with string labels only)
- `app.py` — FastAPI serving app (POST /predict, GET /health)
- `Dockerfile`, `docker-compose.yml` — containerized deployment
- `requirements.txt`
- `metrics.json` — full evaluation metrics
- `openapi.json` — API spec

## Run locally
```bash
pip install -r requirements.txt
uvicorn app:app --reload --port 8000
```

## Run with Docker
```bash
docker compose up --build
```

## Replacing a previous deployment
Drop this package in place of the old one and restart the container --
`app.py` expects `model.pkl` and `preprocessing.pkl` alongside it, so no
code changes are needed on the consuming side as long as the API
contract (`POST /predict` with `{{"records": [...]}}`) is unchanged.

## Metrics
```json
{metrics_json}
```
"""


def generate_deployment_package(
    project_name: str,
    algorithm: str,
    problem_type: str,
    model_object,
    preprocessor,
    metrics: dict,
    overall_score: float,
    label_encoder=None,
    output_dir: str = None,
) -> Path:
    output_dir = Path(output_dir or f"./deployment_output/{project_name}")
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)

    generated_at = datetime.now(timezone.utc).isoformat()

    joblib.dump(model_object, output_dir / "model.pkl")
    joblib.dump(preprocessor, output_dir / "preprocessing.pkl")
    if label_encoder is not None:
        joblib.dump(label_encoder, output_dir / "label_encoder.pkl")

    (output_dir / "app.py").write_text(FASTAPI_APP_TEMPLATE.format(
        project_name=project_name, algorithm=algorithm, problem_type=problem_type, generated_at=generated_at,
    ))
    (output_dir / "Dockerfile").write_text(DOCKERFILE_TEMPLATE)
    (output_dir / "docker-compose.yml").write_text(COMPOSE_TEMPLATE.format(project_name=project_name))
    (output_dir / "requirements.txt").write_text(REQUIREMENTS_TEMPLATE)

    metrics_json = json.dumps(metrics, indent=2, default=str)
    (output_dir / "metrics.json").write_text(metrics_json)

    openapi = json.loads(json.dumps(OPENAPI_SPEC_TEMPLATE).replace("{project_name}", project_name))
    (output_dir / "openapi.json").write_text(json.dumps(openapi, indent=2))

    (output_dir / "README.md").write_text(README_TEMPLATE.format(
        project_name=project_name, generated_at=generated_at, algorithm=algorithm,
        problem_type=problem_type, overall_score=overall_score, metrics_json=metrics_json,
    ))

    zip_path = shutil.make_archive(str(output_dir), "zip", root_dir=output_dir)
    return Path(zip_path)
